# Generated by Django 4.2.6 on 2023-10-15 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0002_bookinstance_borrower'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_mark_returned', 'Set book as returned'),)},
        ),
    ]
